name: Notify Telegram on Release

on:
  release:
    types: [published]

jobs:
  notify:
    runs-on: ubuntu-latest

    steps:
      - name: Send Telegram Notification
        run: |
          curl -X POST "https://api.telegram.org/bot${{ secrets.TELEGRAM_BOT_TOKEN }}/sendMessage" \
          -d "chat_id=${{ secrets.TELEGRAM_CHAT_ID }}" \
          -d "text=新版本发布:\n标题: ${{ github.event.release.name }}\n描述: ${{ github.event.release.body }}\n链接: ${{ github.event.release.html_url }}"
